from datetime import date
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from secpull.income_model import MarginAssumptions
from secpull.model import ModelAssumptions

# ── Layout constants ──────────────────────────────────────────────────────────
_C_LABEL = 1
_C_VAL = 2   # Column B: values / first data column

_R_TITLE = 1
_R_HIST_SECTION = 3
_R_HIST_HEADER = 4
_R_HIST_REVENUE = 5
_R_HIST_GROSS = 6
_R_HIST_GROSS_MARGIN = 7
_R_HIST_OP = 8
_R_HIST_OP_MARGIN = 9
_R_HIST_NET = 10
_R_HIST_NET_MARGIN = 11
_R_HIST_EPS = 12
_R_HIST_SHARES = 13

_R_ASSUMP_SECTION = 15
_R_ASSUMP_HEADER = 16
_R_BEAR_GROWTH = 17
_R_BASE_GROWTH = 18
_R_BULL_GROWTH = 19
_R_GROSS_ASSUMP = 20
_R_OP_ASSUMP = 21
_R_NET_ASSUMP = 22
_R_SHARES_ASSUMP = 23
_R_ASSUMP_NOTE = 24

_R_PROJ_SECTION = 26

# (label_row, header_row, revenue, gross, op_income, net_income, eps)
_SCENARIO_ROWS = {
    "bear": (28, 29, 30, 31, 32, 33, 34),
    "base": (36, 37, 38, 39, 40, 41, 42),
    "bull": (44, 45, 46, 47, 48, 49, 50),
}
_SCENARIO_GROWTH_ROW = {"bear": _R_BEAR_GROWTH, "base": _R_BASE_GROWTH, "bull": _R_BULL_GROWTH}

_R_NOTES_SECTION = 52
_R_NOTES_TEXT = 53

# ── Styles ────────────────────────────────────────────────────────────────────
_FILL_YELLOW = PatternFill("solid", fgColor="FFFF99")
_FILL_GRAY = PatternFill("solid", fgColor="D9D9D9")
_FILL_BLUE = PatternFill("solid", fgColor="BDD7EE")
_BOLD = Font(bold=True)
_ITALIC = Font(italic=True)
_TITLE_FONT = Font(bold=True, size=13)
_PCT_FMT = "0.0%"
_INT_FMT = "#,##0"
_EPS_FMT = "$#,##0.00"
_SHARES_FMT = "#,##0.0"


def add_income_sheet(
    wb: Workbook,
    ticker: str,
    rev_series: list[tuple[int, float]],
    metric_series: dict[str, dict[int, float]],
    margin_assumptions: MarginAssumptions,
    revenue_assumptions: ModelAssumptions,
    proj_years: list[int],
) -> None:
    """Add an 'Income Statement' sheet to an existing workbook.

    rev_series    : [(fiscal_year, raw_dollar_value), ...] sorted ascending
    metric_series : {metric_name: {fiscal_year: raw_dollar_value}}
    proj_years    : [2026, 2027, 2028] — column labels for projection block
    """
    ws = wb.create_sheet(title="Income Statement")

    hist_years = [yr for yr, _ in rev_series]
    n_hist = len(hist_years)
    rev_map = dict(rev_series)
    last_hist_col = get_column_letter(_C_VAL + n_hist - 1)

    gp_map = metric_series.get("gross_profit", {})
    op_map = metric_series.get("operating_income", {})
    net_map = metric_series.get("net_income", {})
    eps_map = metric_series.get("eps_diluted", {})

    # ── Title ─────────────────────────────────────────────────────────────────
    c = ws.cell(_R_TITLE, _C_LABEL)
    c.value = f"{ticker} Income Statement Model — generated by SECPull on {date.today()}"
    c.font = _TITLE_FONT

    # ── Historical section header ─────────────────────────────────────────────
    ws.cell(_R_HIST_SECTION, _C_LABEL).value = "HISTORICAL DATA"
    ws.cell(_R_HIST_SECTION, _C_LABEL).font = _BOLD

    ws.cell(_R_HIST_HEADER, _C_LABEL).value = "Metric"
    ws.cell(_R_HIST_HEADER, _C_LABEL).font = _BOLD
    for i, yr in enumerate(hist_years):
        c = ws.cell(_R_HIST_HEADER, _C_VAL + i)
        c.value = f"FY{yr}"
        c.font = _BOLD
        c.fill = _FILL_GRAY

    # Revenue ($M)
    ws.cell(_R_HIST_REVENUE, _C_LABEL).value = "Revenue ($M)"
    for i, yr in enumerate(hist_years):
        c = ws.cell(_R_HIST_REVENUE, _C_VAL + i)
        c.value = round(rev_map[yr] / 1e6)
        c.number_format = _INT_FMT

    # Gross Profit ($M) and Gross Margin
    ws.cell(_R_HIST_GROSS, _C_LABEL).value = "Gross Profit ($M)"
    ws.cell(_R_HIST_GROSS_MARGIN, _C_LABEL).value = "  Gross Margin"
    for i, yr in enumerate(hist_years):
        col = _C_VAL + i
        col_l = get_column_letter(col)
        c_val = ws.cell(_R_HIST_GROSS, col)
        c_pct = ws.cell(_R_HIST_GROSS_MARGIN, col)
        if yr in gp_map:
            c_val.value = round(gp_map[yr] / 1e6)
            c_val.number_format = _INT_FMT
            c_pct.value = f"={col_l}{_R_HIST_GROSS}/{col_l}{_R_HIST_REVENUE}"
            c_pct.number_format = _PCT_FMT
        else:
            c_val.value = "N/A"
            c_pct.value = "N/A"

    # Operating Income ($M) and Operating Margin
    ws.cell(_R_HIST_OP, _C_LABEL).value = "Operating Income ($M)"
    ws.cell(_R_HIST_OP_MARGIN, _C_LABEL).value = "  Operating Margin"
    for i, yr in enumerate(hist_years):
        col = _C_VAL + i
        col_l = get_column_letter(col)
        c_val = ws.cell(_R_HIST_OP, col)
        c_pct = ws.cell(_R_HIST_OP_MARGIN, col)
        if yr in op_map:
            c_val.value = round(op_map[yr] / 1e6)
            c_val.number_format = _INT_FMT
            c_pct.value = f"={col_l}{_R_HIST_OP}/{col_l}{_R_HIST_REVENUE}"
            c_pct.number_format = _PCT_FMT
        else:
            c_val.value = "N/A"
            c_pct.value = "N/A"

    # Net Income ($M) and Net Margin
    ws.cell(_R_HIST_NET, _C_LABEL).value = "Net Income ($M)"
    ws.cell(_R_HIST_NET_MARGIN, _C_LABEL).value = "  Net Margin"
    for i, yr in enumerate(hist_years):
        col = _C_VAL + i
        col_l = get_column_letter(col)
        c_val = ws.cell(_R_HIST_NET, col)
        c_pct = ws.cell(_R_HIST_NET_MARGIN, col)
        if yr in net_map:
            c_val.value = round(net_map[yr] / 1e6)
            c_val.number_format = _INT_FMT
            c_pct.value = f"={col_l}{_R_HIST_NET}/{col_l}{_R_HIST_REVENUE}"
            c_pct.number_format = _PCT_FMT
        else:
            c_val.value = "N/A"
            c_pct.value = "N/A"

    # EPS Diluted
    ws.cell(_R_HIST_EPS, _C_LABEL).value = "EPS Diluted"
    for i, yr in enumerate(hist_years):
        col = _C_VAL + i
        c = ws.cell(_R_HIST_EPS, col)
        if yr in eps_map:
            c.value = round(eps_map[yr], 2)
            c.number_format = _EPS_FMT
        else:
            c.value = "N/A"

    # Implied Shares (M) = Net Income ($M) / EPS
    ws.cell(_R_HIST_SHARES, _C_LABEL).value = "Implied Shares (M)"
    for i, yr in enumerate(hist_years):
        col = _C_VAL + i
        col_l = get_column_letter(col)
        c = ws.cell(_R_HIST_SHARES, col)
        if yr in net_map and yr in eps_map and eps_map[yr] != 0:
            c.value = f"={col_l}{_R_HIST_NET}/{col_l}{_R_HIST_EPS}"
            c.number_format = _SHARES_FMT
        else:
            c.value = "N/A"

    # ── Assumptions section ───────────────────────────────────────────────────
    ws.cell(_R_ASSUMP_SECTION, _C_LABEL).value = "ASSUMPTIONS  (edit yellow cells to override)"
    ws.cell(_R_ASSUMP_SECTION, _C_LABEL).font = _BOLD

    ws.cell(_R_ASSUMP_HEADER, _C_LABEL).value = "Assumption"
    ws.cell(_R_ASSUMP_HEADER, _C_LABEL).font = _BOLD
    ws.cell(_R_ASSUMP_HEADER, _C_VAL).value = "Value"
    ws.cell(_R_ASSUMP_HEADER, _C_VAL).font = _BOLD
    ws.cell(_R_ASSUMP_HEADER, _C_VAL + 1).value = "Source"

    def _assump(row, label, value, fmt, source=""):
        ws.cell(row, _C_LABEL).value = label
        c = ws.cell(row, _C_VAL)
        if value is None:
            c.value = "N/A"
        else:
            c.value = value
            c.number_format = fmt
            c.fill = _FILL_YELLOW
        ws.cell(row, _C_VAL + 1).value = source

    n = margin_assumptions.n_years_used
    _assump(_R_BEAR_GROWTH, "Revenue Growth — Bear", revenue_assumptions.bear_growth, _PCT_FMT, "Revenue Model")
    _assump(_R_BASE_GROWTH, "Revenue Growth — Base", revenue_assumptions.base_growth, _PCT_FMT, "Revenue Model")
    _assump(_R_BULL_GROWTH, "Revenue Growth — Bull", revenue_assumptions.bull_growth, _PCT_FMT, "Revenue Model")
    _assump(_R_GROSS_ASSUMP, "Gross Margin %",
            margin_assumptions.gross_margin, _PCT_FMT,
            f"{n}-yr avg" if margin_assumptions.gross_margin is not None else "No data — enter to enable")
    _assump(_R_OP_ASSUMP, "Operating Margin %",
            margin_assumptions.operating_margin, _PCT_FMT,
            f"{n}-yr avg" if margin_assumptions.operating_margin is not None else "No data — enter to enable")
    _assump(_R_NET_ASSUMP, "Net Margin %",
            margin_assumptions.net_margin, _PCT_FMT,
            f"{n}-yr avg" if margin_assumptions.net_margin is not None else "No data — enter to enable")
    _assump(_R_SHARES_ASSUMP, "Diluted Shares (M)",
            margin_assumptions.diluted_shares_m, _SHARES_FMT,
            "Most recent implied" if margin_assumptions.diluted_shares_m is not None else "No data — enter to enable")

    c = ws.cell(_R_ASSUMP_NOTE, _C_LABEL)
    c.value = (
        f"Margins are {n}-year historical averages from SEC filings. "
        "N/A means the metric was absent from EDGAR — enter a number to enable that row's projections."
    )
    c.font = _ITALIC

    # ── Projections section ───────────────────────────────────────────────────
    ws.cell(_R_PROJ_SECTION, _C_LABEL).value = "PROJECTIONS ($M, except EPS)"
    ws.cell(_R_PROJ_SECTION, _C_LABEL).font = _BOLD

    has_gross = margin_assumptions.gross_margin is not None
    has_op = margin_assumptions.operating_margin is not None
    has_net = margin_assumptions.net_margin is not None
    has_shares = margin_assumptions.diluted_shares_m is not None

    for scenario, (r_lbl, r_hdr, r_rev, r_gross, r_op, r_net, r_eps) in _SCENARIO_ROWS.items():
        r_growth = _SCENARIO_GROWTH_ROW[scenario]

        ws.cell(r_lbl, _C_LABEL).value = scenario.upper()
        ws.cell(r_lbl, _C_LABEL).font = _BOLD

        ws.cell(r_hdr, _C_LABEL).value = "Metric"
        ws.cell(r_hdr, _C_LABEL).font = _BOLD
        for i, yr in enumerate(proj_years):
            c = ws.cell(r_hdr, _C_VAL + i)
            c.value = f"FY{yr}"
            c.font = _BOLD
            c.fill = _FILL_BLUE

        for row, label in (
            (r_rev, "Revenue ($M)"),
            (r_gross, "Gross Profit ($M)"),
            (r_op, "Operating Income ($M)"),
            (r_net, "Net Income ($M)"),
            (r_eps, "EPS Diluted"),
        ):
            ws.cell(row, _C_LABEL).value = label

        for i in range(len(proj_years)):
            col = _C_VAL + i
            col_l = get_column_letter(col)
            rev_cell = f"{col_l}{r_rev}"

            # Revenue — chains from prior year (year 0 anchors to last historical)
            if i == 0:
                rev_formula = f"={last_hist_col}{_R_HIST_REVENUE}*(1+$B${r_growth})"
            else:
                prev_l = get_column_letter(col - 1)
                rev_formula = f"={prev_l}{r_rev}*(1+$B${r_growth})"
            c = ws.cell(r_rev, col)
            c.value = rev_formula
            c.number_format = _INT_FMT

            # Gross Profit = Revenue × Gross Margin assumption
            c = ws.cell(r_gross, col)
            if has_gross:
                c.value = f"={rev_cell}*$B${_R_GROSS_ASSUMP}"
                c.number_format = _INT_FMT
            else:
                c.value = "N/A"

            # Operating Income = Revenue × Op Margin assumption
            c = ws.cell(r_op, col)
            if has_op:
                c.value = f"={rev_cell}*$B${_R_OP_ASSUMP}"
                c.number_format = _INT_FMT
            else:
                c.value = "N/A"

            # Net Income = Revenue × Net Margin assumption
            c = ws.cell(r_net, col)
            if has_net:
                c.value = f"={rev_cell}*$B${_R_NET_ASSUMP}"
                c.number_format = _INT_FMT
            else:
                c.value = "N/A"

            # EPS = Net Income ($M) / Shares (M)
            c = ws.cell(r_eps, col)
            if has_net and has_shares:
                c.value = f"={col_l}{r_net}/$B${_R_SHARES_ASSUMP}"
                c.number_format = _EPS_FMT
            else:
                c.value = "N/A"

    # ── Notes ─────────────────────────────────────────────────────────────────
    ws.cell(_R_NOTES_SECTION, _C_LABEL).value = "MODEL NOTES"
    ws.cell(_R_NOTES_SECTION, _C_LABEL).font = _BOLD
    c = ws.cell(_R_NOTES_TEXT, _C_LABEL)
    c.value = (
        "Revenue compounds annually: Revenue(t) = Revenue(t-1) × (1 + growth_rate). "
        "All other line items are driven by revenue: e.g. Gross Profit = Revenue × Gross Margin %. "
        "EPS = Net Income ($M) ÷ Diluted Shares (M). "
        "Yellow cells are editable — changing any assumption instantly updates all downstream projections. "
        "N/A means the metric was absent from EDGAR filings for this company; "
        "enter a number in the yellow cell to activate that row."
    )
    c.alignment = Alignment(wrap_text=True)

    # ── Column widths ─────────────────────────────────────────────────────────
    ws.column_dimensions["A"].width = 28
    ws.column_dimensions[get_column_letter(_C_VAL + 1)].width = 26  # source column
    for i in range(max(n_hist, len(proj_years)) + 1):
        ws.column_dimensions[get_column_letter(_C_VAL + i)].width = 14
    ws.row_dimensions[_R_NOTES_TEXT].height = 60
