from datetime import date
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from secpull.model import ModelAssumptions

# ── Layout constants (row / column indices) ──────────────────────────────────
_C_LABEL = 1       # Column A: row labels
_C_FIRST_DATA = 2  # Column B: first data column

_R_TITLE = 1
_R_HIST_SECTION = 3
_R_HIST_HEADER = 4
_R_REVENUE = 5
_R_GROWTH = 6
_R_ASSUMP_SECTION = 8
_R_BEAR = 9
_R_BASE = 10
_R_BULL = 11
_R_ASSUMP_NOTE = 12
_R_PROJ_SECTION = 14
_R_PROJ_HEADER = 15
_R_PROJ_BEAR = 16
_R_PROJ_BASE = 17
_R_PROJ_BULL = 18
_R_NOTES_SECTION = 20
_R_NOTES_TEXT = 21

# ── Styles ───────────────────────────────────────────────────────────────────
_FILL_YELLOW = PatternFill("solid", fgColor="FFFF99")   # editable assumptions
_FILL_GRAY = PatternFill("solid", fgColor="D9D9D9")     # historical headers
_FILL_BLUE = PatternFill("solid", fgColor="BDD7EE")     # projection headers
_BOLD = Font(bold=True)
_ITALIC = Font(italic=True)
_TITLE_FONT = Font(bold=True, size=13)
_PCT_FMT = "0.0%"
_INT_FMT = "#,##0"


def export_model_xlsx(
    ticker: str,
    rev_series: list[tuple[int, float]],
    assumptions: ModelAssumptions,
    projections: dict[str, list[tuple[int, float]]],
    out_path: Path,
) -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "Revenue Model"

    n_hist = len(rev_series)
    last_hist_col = get_column_letter(_C_FIRST_DATA + n_hist - 1)
    last_hist_cell = f"{last_hist_col}{_R_REVENUE}"

    # Fixed absolute references for assumption cells (used in projection formulas)
    _bear_ref = f"$B${_R_BEAR}"
    _base_ref = f"$B${_R_BASE}"
    _bull_ref = f"$B${_R_BULL}"

    # ── Row 1: Title ──────────────────────────────────────────────────────────
    cell = ws.cell(_R_TITLE, _C_LABEL)
    cell.value = f"{ticker} Revenue Model — generated by SECPull on {date.today()}"
    cell.font = _TITLE_FONT

    # ── Row 3: Historical section header ──────────────────────────────────────
    ws.cell(_R_HIST_SECTION, _C_LABEL).value = "HISTORICAL DATA"
    ws.cell(_R_HIST_SECTION, _C_LABEL).font = _BOLD

    # ── Row 4: Historical column headers ─────────────────────────────────────
    ws.cell(_R_HIST_HEADER, _C_LABEL).value = "Metric"
    ws.cell(_R_HIST_HEADER, _C_LABEL).font = _BOLD
    for i, (yr, _) in enumerate(rev_series):
        c = ws.cell(_R_HIST_HEADER, _C_FIRST_DATA + i)
        c.value = f"FY{yr}"
        c.font = _BOLD
        c.fill = _FILL_GRAY

    # ── Row 5: Revenue values ($M, rounded) ───────────────────────────────────
    ws.cell(_R_REVENUE, _C_LABEL).value = "Revenue ($M)"
    for i, (_, val) in enumerate(rev_series):
        c = ws.cell(_R_REVENUE, _C_FIRST_DATA + i)
        c.value = round(val / 1e6)
        c.number_format = _INT_FMT

    # ── Row 6: YoY growth (formula for all except first column) ───────────────
    ws.cell(_R_GROWTH, _C_LABEL).value = "YoY Growth"
    ws.cell(_R_GROWTH, _C_FIRST_DATA).value = "N/A"
    for i in range(1, n_hist):
        col = _C_FIRST_DATA + i
        cur = get_column_letter(col)
        prv = get_column_letter(col - 1)
        c = ws.cell(_R_GROWTH, col)
        c.value = f"=({cur}{_R_REVENUE}/{prv}{_R_REVENUE})-1"
        c.number_format = _PCT_FMT

    # ── Row 8: Assumptions section header ─────────────────────────────────────
    ws.cell(_R_ASSUMP_SECTION, _C_LABEL).value = "ASSUMPTIONS  (edit yellow cells to override)"
    ws.cell(_R_ASSUMP_SECTION, _C_LABEL).font = _BOLD

    # ── Rows 9–11: Editable assumption cells ──────────────────────────────────
    for row, label, value in (
        (_R_BEAR, "Bear Growth Rate", assumptions.bear_growth),
        (_R_BASE, "Base Growth Rate", assumptions.base_growth),
        (_R_BULL, "Bull Growth Rate", assumptions.bull_growth),
    ):
        ws.cell(row, _C_LABEL).value = label
        c = ws.cell(row, _C_FIRST_DATA)
        c.value = value
        c.number_format = _PCT_FMT
        c.fill = _FILL_YELLOW

    # ── Row 12: Assumption note ───────────────────────────────────────────────
    c = ws.cell(_R_ASSUMP_NOTE, _C_LABEL)
    c.value = (
        f"Base = {assumptions.n_years_used}-year historical average. "
        "Bear = Base − 5 pp.  Bull = Base + 5 pp.  Edit yellow cells to run your own scenarios."
    )
    c.font = _ITALIC

    # ── Row 14: Projections section header ────────────────────────────────────
    ws.cell(_R_PROJ_SECTION, _C_LABEL).value = "PROJECTIONS ($M)"
    ws.cell(_R_PROJ_SECTION, _C_LABEL).font = _BOLD

    # ── Row 15: Projection column headers ─────────────────────────────────────
    proj_years = [yr for yr, _ in projections["base"]]
    ws.cell(_R_PROJ_HEADER, _C_LABEL).value = "Scenario"
    ws.cell(_R_PROJ_HEADER, _C_LABEL).font = _BOLD
    for i, yr in enumerate(proj_years):
        c = ws.cell(_R_PROJ_HEADER, _C_FIRST_DATA + i)
        c.value = f"FY{yr}"
        c.font = _BOLD
        c.fill = _FILL_BLUE

    # ── Rows 16–18: Projection formulas ──────────────────────────────────────
    for row, assump_ref in (
        (_R_PROJ_BEAR, _bear_ref),
        (_R_PROJ_BASE, _base_ref),
        (_R_PROJ_BULL, _bull_ref),
    ):
        label = {_R_PROJ_BEAR: "Bear", _R_PROJ_BASE: "Base", _R_PROJ_BULL: "Bull"}[row]
        ws.cell(row, _C_LABEL).value = label
        for i in range(len(proj_years)):
            col = _C_FIRST_DATA + i
            col_letter = get_column_letter(col)
            if i == 0:
                formula = f"={last_hist_cell}*(1+{assump_ref})"
            else:
                prev_col = get_column_letter(col - 1)
                formula = f"={prev_col}{row}*(1+{assump_ref})"
            c = ws.cell(row, col)
            c.value = formula
            c.number_format = _INT_FMT

    # ── Row 20: Notes section ─────────────────────────────────────────────────
    ws.cell(_R_NOTES_SECTION, _C_LABEL).value = "MODEL NOTES"
    ws.cell(_R_NOTES_SECTION, _C_LABEL).font = _BOLD

    c = ws.cell(_R_NOTES_TEXT, _C_LABEL)
    c.value = (
        "Historical revenue is sourced from SEC 10-K filings via the EDGAR XBRL API. "
        "YoY growth is computed year-over-year between consecutive fiscal years only — "
        "a gap in the series produces N/A rather than a bridged estimate. "
        f"The Base growth rate is the mean of the last {assumptions.n_years_used} available "
        "annual growth rates. Bear subtracts 5 percentage points; Bull adds 5 percentage points. "
        "Each projection year compounds from the prior year using the formula: "
        "Revenue(t) = Revenue(t-1) × (1 + growth_rate). "
        "Yellow cells are editable assumptions — change them to run your own scenarios."
    )
    c.alignment = Alignment(wrap_text=True)

    # ── Column widths ─────────────────────────────────────────────────────────
    ws.column_dimensions["A"].width = 30
    for i in range(n_hist + len(proj_years)):
        ws.column_dimensions[get_column_letter(_C_FIRST_DATA + i)].width = 13
    ws.row_dimensions[_R_NOTES_TEXT].height = 60

    wb.save(out_path)
